### ISSUE TITLE
Scala Interpreter Fails with JDK 9.0.X

### ISSUE THREAD

**Issue by skotchpine** [skotchpine/asdf-java#3]
Using the JDK 9.0.1 version causes the scala interpreter to crash. Possibly a corrupted jar?

```sh
asdf global java 8.141
scala
```
```
Welcome to Scala 2.12.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_141).
Type in expressions for evaluation. Or try :help.

scala>
```

```sh
asdf global java 9.0.1
scala
```
```
Welcome to Scala 2.12.0 (Java HotSpot(TM) 64-Bit Server VM, Java 9.0.1).
Type in expressions for evaluation. Or try :help.

scala> 
Failed to initialize compiler: object java.lang.Object in compiler mirror not found.
** Note that as of 2.8 scala does not assume use of the java classpath.
** For the old behavior pass -usejavacp to scala, or if using a Settings
** object programmatically, settings.usejavacp.value = true.

Failed to initialize compiler: object java.lang.Object in compiler mirror not found.
** Note that as of 2.8 scala does not assume use of the java classpath.
** For the old behavior pass -usejavacp to scala, or if using a Settings
** object programmatically, settings.usejavacp.value = true.
Exception in thread "main" scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$getModuleOrClass$4(Mirrors.scala:54)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:54)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:267)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:267)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1447)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1126)
	at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:427)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:801)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:759)
	at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:624)
	at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:658)
	at scala.tools.nsc.interpreter.IMain.$anonfun$quietBind$1(IMain.scala:657)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:209)
	at scala.tools.nsc.interpreter.IMain.quietBind(IMain.scala:657)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$process$5(ILoop.scala:911)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$mumly$1(ILoop.scala:188)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:209)
	at scala.tools.nsc.interpreter.ILoop.mumly(ILoop.scala:185)
	at scala.tools.nsc.interpreter.ILoop.loopPostInit$1(ILoop.scala:908)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$process$11(ILoop.scala:979)
	at scala.tools.nsc.interpreter.ILoop.startup$1(ILoop.scala:947)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$process$1(ILoop.scala:990)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:892)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:79)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:92)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
cat out
Exception in thread "Thread-1" java.lang.InterruptedException
	at java.base/java.util.concurrent.SynchronousQueue.put(SynchronousQueue.java:875)
	at scala.tools.nsc.interpreter.SplashLoop.run(InteractiveReader.scala:77)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by skotchpine** [comment]
I see a similar (possibly the same) issue with 9.0.4

**Comment by skotchpine** [comment]
This seems to be a problem with a few specific scala builds. I'm going to close this issue, because It's not relevant enough.
